easy_admin:
    entities:
        Advert:
            class : App\Entity\Advert
            form :
                fields:
                  - {property: 'Title'}
                  - {property: 'Price'}
                  - {property: 'Brand'}
                  - {property: 'Size'}
                  - {property: 'Category'}
                  - { property: 'imageFile', type: 'file' }

        AdvertLike:
            class : App\Entity\AdvertLike
        Category:
            class : App\Entity\Category
        User:
            class : App\Entity\User

